/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.views;

import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sk.stu.fiit.controllers.EmployerManagerController;

/**
 *
 * @author Admin
 */
public class AddCompanyView extends javax.swing.JFrame {
    
    private final EmployersView parent;
    private final EmployerManagerController controller;

    /**
     * Creates new form AddCompanyView
     * @param parent
     * @param controller
     */
    public AddCompanyView(EmployersView parent, EmployerManagerController controller) {
        this.parent = parent;
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        confirmBtn = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        goMenuBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        sectorTF = new javax.swing.JTextField();
        noeSpinner = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        confirmBtn1 = new javax.swing.JButton();
        jToolBar4 = new javax.swing.JToolBar();
        goBackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pathTF = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(380, 400));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(380, 400));

        jPanel1.setMinimumSize(new java.awt.Dimension(380, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        confirmBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        confirmBtn.setText("Potvrdiť");
        confirmBtn.setPreferredSize(new java.awt.Dimension(80, 28));
        confirmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                confirmBtnMouseReleased(evt);
            }
        });
        jToolBar1.add(confirmBtn);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 80, 40));

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        goMenuBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        goMenuBtn.setText("Návrat");
        goMenuBtn.setPreferredSize(new java.awt.Dimension(80, 28));
        goMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                goMenuBtnMouseReleased(evt);
            }
        });
        jToolBar2.add(goMenuBtn);

        jPanel1.add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 90, 40));

        jLabel13.setText("Meno");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 30));

        jLabel12.setText("Počet zamestnancov");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        jLabel14.setText("Oblasť podnikania");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 30));
        jPanel1.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 220, -1));
        jPanel1.add(sectorTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 220, -1));

        noeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        jPanel1.add(noeSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 70, -1));

        jTabbedPane1.addTab("Základné údaje", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        confirmBtn1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        confirmBtn1.setText("Potvrdiť");
        confirmBtn1.setPreferredSize(new java.awt.Dimension(80, 28));
        confirmBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                confirmBtn1MouseReleased(evt);
            }
        });
        jToolBar3.add(confirmBtn1);

        jPanel2.add(jToolBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 80, 40));

        jToolBar4.setFloatable(false);
        jToolBar4.setRollover(true);

        goBackBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        goBackBtn.setText("Návrat");
        goBackBtn.setPreferredSize(new java.awt.Dimension(80, 28));
        goBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                goBackBtnMouseReleased(evt);
            }
        });
        jToolBar4.add(goBackBtn);

        jPanel2.add(jToolBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 90, 40));

        jLabel1.setText("Zadajte cestu k logu:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 30));
        jPanel2.add(pathTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 230, -1));

        jTabbedPane1.addTab("Logo", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 2, -1, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmBtnMouseReleased
        // TODO add your handling code here:       
        goToNextTab();
    }//GEN-LAST:event_confirmBtnMouseReleased

    private void goMenuBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goMenuBtnMouseReleased
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_goMenuBtnMouseReleased

    private void confirmBtn1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmBtn1MouseReleased
        // TODO add your handling code here:
        String name = nameTF.getText();
        String sector = sectorTF.getText();
        int noe;
        try {
            noe = getNOE();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(parent, "nespávny formát počtu zamestnancov");
            return;
        }
        String pathToImage = pathTF.getText();
        try {
            this.controller.addEmployer(name, sector, noe, pathToImage);
            this.parent.displayEmployers();
            dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(parent, "Súbor sa nenašiel");
        }
    }//GEN-LAST:event_confirmBtn1MouseReleased

    private void goBackBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseReleased
        // TODO add your handling code here:
        goToPrevTab();
    }//GEN-LAST:event_goBackBtnMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton confirmBtn1;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JButton goMenuBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JTextField nameTF;
    private javax.swing.JSpinner noeSpinner;
    private javax.swing.JTextField pathTF;
    private javax.swing.JTextField sectorTF;
    // End of variables declaration//GEN-END:variables

    private void goToNextTab() {
        int currentIndex = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(currentIndex + 1);
    }
    private void goToPrevTab() {
        int currentIndex = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(currentIndex - 1);
    }

    private int getNOE() throws ParseException {
        noeSpinner.commitEdit();
        System.out.println((Integer) noeSpinner.getValue());
        return (Integer) noeSpinner.getValue();
    }
}
