/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.views;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import sk.stu.fiit.controllers.EmployerManagerController;

/**
 *
 * @author Admin
 */
public final class EmployersView extends javax.swing.JFrame implements DarkNimbus{
    
    private final EmployerManagerController controller = new EmployerManagerController();

    /**
     * Creates new form EmployersView
     */
    public EmployersView() {
        initComponents();
        setDarkNimbus();
        displayEmployers();
        this.setTitle("Prehľad spoločností");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        employersSP = new javax.swing.JScrollPane();
        employersList = new javax.swing.JList<>();
        jToolBar1 = new javax.swing.JToolBar();
        manageEmployer = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        goBackBtn = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employersSP.setViewportView(employersList);

        jDesktopPane1.add(employersSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 190));

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        manageEmployer.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        manageEmployer.setText("Spravovať");
        manageEmployer.setFocusable(false);
        manageEmployer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        manageEmployer.setPreferredSize(new java.awt.Dimension(122, 28));
        manageEmployer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        manageEmployer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                manageEmployerMouseReleased(evt);
            }
        });
        jToolBar1.add(manageEmployer);

        addBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        addBtn.setText("Pridať");
        addBtn.setFocusable(false);
        addBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addBtn.setPreferredSize(new java.awt.Dimension(122, 28));
        addBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addBtnMouseReleased(evt);
            }
        });
        jToolBar1.add(addBtn);

        jDesktopPane1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 110, -1));

        jLabel1.setFont(new java.awt.Font("Segoe WP", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zoznam spoločností");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, -1));

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        goBackBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        goBackBtn.setText("Návrat");
        goBackBtn.setMaximumSize(new java.awt.Dimension(6, 28));
        goBackBtn.setPreferredSize(new java.awt.Dimension(122, 28));
        goBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                goBackBtnMouseReleased(evt);
            }
        });
        jToolBar2.add(goBackBtn);

        jDesktopPane1.add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageEmployerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEmployerMouseReleased
        // TODO add your handling code here:
        int selectedIndex = employersList.getSelectedIndex();
        if(selectedIndex < 0){
            JOptionPane.showMessageDialog(rootPane, "Vyberte spoločnosť");
        } else{
            new ManageEmployerView(this.controller, selectedIndex).setVisible(true);
        }       
    }//GEN-LAST:event_manageEmployerMouseReleased

    private void goBackBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseReleased
        // TODO add your handling code here:
        new InitView().setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackBtnMouseReleased

    private void addBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseReleased
        // TODO add your handling code here:
        new AddCompanyView(this, this.controller).setVisible(true);
    }//GEN-LAST:event_addBtnMouseReleased
    public void displayEmployers(){
        DefaultListModel quickModel = controller.getQuickModel();
        this.employersList.setModel(quickModel);
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployersView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JList<String> employersList;
    private javax.swing.JScrollPane employersSP;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton manageEmployer;
    // End of variables declaration//GEN-END:variables
}
