/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.views;

/**
 *
 * @author Admin
 */
public class InitView extends javax.swing.JFrame implements DarkNimbus{

    /**
     * Creates new form InitView
     */
    public InitView() {
        initComponents();
        setDarkNimbus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        companiesBtn = new javax.swing.JButton();
        specialistsBtn = new javax.swing.JButton();
        jobsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.setLayout(new net.miginfocom.swing.MigLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 0, 0));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(250, 100));

        companiesBtn.setBackground(new java.awt.Color(255, 0, 51));
        companiesBtn.setFont(new java.awt.Font("Segoe WP", 1, 18)); // NOI18N
        companiesBtn.setForeground(new java.awt.Color(255, 255, 255));
        companiesBtn.setText("Spoločnosti");
        companiesBtn.setFocusable(false);
        companiesBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        companiesBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        companiesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                companiesBtnMouseReleased(evt);
            }
        });
        jToolBar1.add(companiesBtn);

        specialistsBtn.setBackground(new java.awt.Color(255, 0, 51));
        specialistsBtn.setFont(new java.awt.Font("Segoe WP", 1, 18)); // NOI18N
        specialistsBtn.setForeground(new java.awt.Color(255, 255, 255));
        specialistsBtn.setText("IT Freelanceri");
        specialistsBtn.setFocusable(false);
        specialistsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        specialistsBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        specialistsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                specialistsBtnMouseReleased(evt);
            }
        });
        jToolBar1.add(specialistsBtn);

        jobsBtn.setBackground(new java.awt.Color(255, 0, 51));
        jobsBtn.setFont(new java.awt.Font("Segoe WP", 1, 18)); // NOI18N
        jobsBtn.setForeground(new java.awt.Color(255, 255, 255));
        jobsBtn.setText("Pracovné ponuky");
        jobsBtn.setFocusable(false);
        jobsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jobsBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jobsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jobsBtnMouseReleased(evt);
            }
        });
        jToolBar1.add(jobsBtn);

        jDesktopPane1.add(jToolBar1);

        jLabel1.setFont(new java.awt.Font("Segoe WP", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("IT Profesia");
        jDesktopPane1.add(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void companiesBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companiesBtnMouseReleased
        // TODO add your handling code here:
        new EmployersView().setVisible(true);
        dispose();
    }//GEN-LAST:event_companiesBtnMouseReleased

    private void specialistsBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specialistsBtnMouseReleased
        // TODO add your handling code here:
        new SpecialistsView().setVisible(true);
        dispose();
    }//GEN-LAST:event_specialistsBtnMouseReleased

    private void jobsBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobsBtnMouseReleased
        // TODO add your handling code here:
        new JobsView().setVisible(true);
        dispose();
    }//GEN-LAST:event_jobsBtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton companiesBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jobsBtn;
    private javax.swing.JButton specialistsBtn;
    // End of variables declaration//GEN-END:variables
}
